"""
Brevo (formerly Sendinblue) API wrapper – Stage 4.

Sends one transactional email per verified contact via Brevo's
POST /v3/smtp/email endpoint.

Endpoint (confirmed from public Brevo docs):
    POST https://api.brevo.com/v3/smtp/email
    Headers: { "api-key": "<BREVO_API_KEY>" }
    Body:
    {
        "sender":     { "name": "...", "email": "..." },
        "to":         [{ "email": "...", "name": "..." }],
        "subject":    "...",
        "htmlContent": "...",
        "textContent": "..."
    }

Design decisions:
- One API call per contact (Brevo's transactional endpoint is per-message).
- Fan-out is bounded by CONCURRENT_REQUESTS semaphore to avoid 429s.
- A failure on one send does NOT abort the rest; failures are collected and
  returned in BrevoResult.emails_failed for post-run inspection.
- Both htmlContent and textContent are sent so mail clients without HTML
  rendering still get a readable message.
- Email body is generated by a pure function `_build_email_body` – easy to
  unit-test and swap for a Jinja2 template later without touching the HTTP layer.
"""

from __future__ import annotations

import asyncio
import textwrap

import aiohttp

from core.config import get_config
from core.logger import get_logger
from models.schemas import BrevoResult, SentEmail, VerifiedContact
from services.base import BaseAPIClient
from utils.retry import async_retry

logger = get_logger(__name__)
cfg = get_config()


# ---------------------------------------------------------------------------
# Email template
# ---------------------------------------------------------------------------

def _build_email_body(contact: VerifiedContact) -> tuple[str, str, str]:
    """
    Returns (subject, html_body, plain_text_body) personalised to the contact.

    Value proposition: B2B SaaS that automates technical candidate screening.
    Tone: professional, concise, non-spammy. One concrete pain-point, one CTA.
    """
    first = contact.first_name or contact.full_name.split()[0]
    company = contact.company_name or "your company"
    title = contact.title or "your role"

    subject = f"Cutting technical screening time at {company} by 60%"

    plain = textwrap.dedent(f"""\
        Hi {first},

        I came across {company} and noticed the engineering team has been scaling \
quickly — congratulations on the growth.

        One challenge that typically comes with that growth is the volume of \
technical interviews. Screening candidates manually is expensive: each \
hire consumes 15–20 hours of senior engineer time before a single offer \
is made.

        We built ScreenIQ to solve exactly that. ScreenIQ is a B2B SaaS platform \
that automates the technical screening stage — coding assessments, live \
evaluation, and AI-powered scoring — so your team only interviews \
candidates who have already proven themselves. Companies like yours \
typically cut screening time by 60% and reduce time-to-hire by three weeks.

        Given your position as {title} at {company}, I thought this might be \
worth a 20-minute call. I'm happy to share a live demo and a \
tailored ROI estimate for your current hiring volume.

        Would Thursday or Friday this week work, or feel free to grab a slot \
directly: https://calendly.com/screeniq/demo

        Best,
        {cfg.BREVO_SENDER_NAME}
        {cfg.BREVO_SENDER_EMAIL}

        ScreenIQ — Automate screening. Hire faster.
        Unsubscribe: https://screeniq.io/unsubscribe
    """)

    html = f"""\
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="font-family:Arial,sans-serif;font-size:15px;line-height:1.6;color:#222;max-width:620px;margin:0 auto;padding:24px;">
  <p>Hi {first},</p>
  <p>
    I came across <strong>{company}</strong> and noticed the engineering team has been
    scaling quickly — congratulations on the growth.
  </p>
  <p>
    One challenge that typically comes with that growth is the volume of technical
    interviews. Screening candidates manually is expensive: each hire consumes
    <strong>15–20 hours of senior engineer time</strong> before a single offer is made.
  </p>
  <p>
    We built <strong>ScreenIQ</strong> to solve exactly that. ScreenIQ is a B2B SaaS
    platform that automates the technical screening stage — coding assessments, live
    evaluation, and AI-powered scoring — so your team only interviews candidates who
    have <em>already proven themselves</em>. Companies like yours typically cut
    screening time by <strong>60%</strong> and reduce time-to-hire by three weeks.
  </p>
  <p>
    Given your position as <strong>{title}</strong> at {company}, I thought this might
    be worth a 20-minute call. I'm happy to share a live demo and a tailored ROI
    estimate for your current hiring volume.
  </p>
  <p>
    Would Thursday or Friday this week work, or feel free to grab a slot directly:<br>
    <a href="https://calendly.com/screeniq/demo">https://calendly.com/screeniq/demo</a>
  </p>
  <p>
    Best,<br>
    <strong>{cfg.BREVO_SENDER_NAME}</strong><br>
    <a href="mailto:{cfg.BREVO_SENDER_EMAIL}">{cfg.BREVO_SENDER_EMAIL}</a>
  </p>
  <hr style="border:none;border-top:1px solid #eee;margin:24px 0;">
  <p style="font-size:12px;color:#999;">
    ScreenIQ — Automate screening. Hire faster.<br>
    <a href="https://screeniq.io/unsubscribe" style="color:#999;">Unsubscribe</a>
  </p>
</body>
</html>"""

    return subject, html, plain


# ---------------------------------------------------------------------------
# Service class
# ---------------------------------------------------------------------------

class BrevoService(BaseAPIClient):
    base_url = cfg.BREVO_BASE_URL

    def _headers(self) -> dict:
        return {
            "api-key": cfg.BREVO_API_KEY,  # Brevo uses 'api-key' header, NOT Bearer.
            "Content-Type": "application/json",
            "Accept": "application/json",
        }

    @async_retry(
        max_attempts=cfg.MAX_RETRIES,
        base_delay=cfg.RETRY_BASE_DELAY,
        exceptions=(aiohttp.ClientError, aiohttp.ServerConnectionError, asyncio.TimeoutError),
    )
    async def _send_single(self, contact: VerifiedContact) -> dict:
        """Make one Brevo transactional send request."""
        subject, html_body, text_body = _build_email_body(contact)
        payload = {
            "sender": {
                "name": cfg.BREVO_SENDER_NAME,
                "email": cfg.BREVO_SENDER_EMAIL,
            },
            "to": [{"email": contact.email, "name": contact.full_name}],
            "subject": subject,
            "htmlContent": html_body,
            "textContent": text_body,
        }
        return await self._post("/smtp/email", headers=self._headers(), payload=payload)

    async def _send_one(
        self, contact: VerifiedContact
    ) -> tuple[SentEmail | None, dict | None]:
        """
        Send to one contact; return (SentEmail, None) on success or
        (None, failure_dict) on error — never raises.
        """
        try:
            raw = await self._send_single(contact)
            message_id = raw.get("messageId") or raw.get("message_id")
            sent = SentEmail(
                recipient_email=contact.email,
                recipient_name=contact.full_name,
                company_name=contact.company_name,
                message_id=str(message_id) if message_id else None,
                status="sent",
            )
            logger.info(
                "[Stage 4] Email sent → %s (%s) | messageId=%s",
                contact.email,
                contact.full_name,
                message_id,
            )
            return sent, None
        except Exception as exc:
            logger.error(
                "[Stage 4] Failed to send to %s (%s): %s",
                contact.email,
                contact.full_name,
                exc,
            )
            return None, {
                "email": contact.email,
                "name": contact.full_name,
                "error": str(exc),
            }

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    async def send_emails(self, contacts: list[VerifiedContact]) -> BrevoResult:
        """
        Fan-out email sends across all verified contacts.
        Bounded by CONCURRENT_REQUESTS semaphore.
        Partial failures are collected; they do NOT abort the run.
        """
        logger.info("[Stage 4] Sending emails to %d contacts.", len(contacts))
        sem = asyncio.Semaphore(cfg.CONCURRENT_REQUESTS)

        async def bounded(contact: VerifiedContact):
            async with sem:
                return await self._send_one(contact)

        outcomes = await asyncio.gather(*[bounded(c) for c in contacts])

        sent: list[SentEmail] = []
        failed: list[dict] = []
        for ok, err in outcomes:
            if ok:
                sent.append(ok)
            if err:
                failed.append(err)

        logger.info(
            "[Stage 4] Done. Sent=%d, Failed=%d.", len(sent), len(failed)
        )
        return BrevoResult(emails_sent=sent, emails_failed=failed)

    async def send_emails_mock(self, contacts: list[VerifiedContact]) -> BrevoResult:
        """Mock send – logs what would have been sent without hitting Brevo."""
        logger.info("[Stage 4][MOCK] Simulating email sends for %d contacts.", len(contacts))
        sent: list[SentEmail] = []
        for contact in contacts:
            subject, _, _ = _build_email_body(contact)
            logger.info(
                "[Stage 4][MOCK] Would send to %s | subject: %s",
                contact.email,
                subject,
            )
            sent.append(
                SentEmail(
                    recipient_email=contact.email,
                    recipient_name=contact.full_name,
                    company_name=contact.company_name,
                    message_id=f"mock-{contact.email}",
                    status="mock_sent",
                )
            )
        return BrevoResult(emails_sent=sent, emails_failed=[])